image: $DOCKER_REGISTRY_PREFIX/2smart/utils/combined-ci-image:latest

stages:
  - build
  - release

services:
  - name: registry.gitlab.webbylab.com/smarthome/base-images/docker-dind
    alias: docker

build:
  stage: build
  script:
    - git clone https://oauth2:$ACCESS_TOKEN@gitlab.webbylab.com/SmartHome/docker-utils.git
    - mv docker-utils/utils.sh docker.sh
    - ./docker.sh rundaemon
    - ./docker.sh build
    - ./docker.sh push
    - ./docker.sh push_bridge_type_to_demo
  only:
    - 'master'

release:
  stage: release
  script:
    - git clone https://oauth2:$ACCESS_TOKEN@gitlab.webbylab.com/SmartHome/docker-utils.git
    - mv docker-utils/utils.sh docker.sh
    - ./docker.sh rundaemon
    - ./docker.sh release_bridge_type
  only:
    - 'release'